"""CPU-only explicit continuation of ten never-started non-Dynamo cells."""
from pathlib import Path
import copy,re,sys,time,json
B=Path(__file__).resolve().parent;sys.path.insert(0,str(B));import baseline_reconciliation_v3 as q
p=q.p;previous=B/'baseline-reconciliation-004/declaration.json';aborted=B/'baselines-reconciled-004/status.json'
s=p.read(aborted);p.need(s['attempted']==s['completed']==s['failed']==[] and s['node_lease_held'] is False and s['error']=="BlockingIOError(11, 'Resource temporarily unavailable')",'only known lease-conflict zero-observation queue may continue unchanged')
d=copy.deepcopy(q.audit(previous));d['created_s']=time.time();d['prior_stages'].append({'status':p.ref(aborted)});d.update(scope_authorization='Retain all original observations and three old Dynamo repeat2 retirements. Ten non-Dynamo unstarted points after external owner restoration/fresh native qualification, then original Eco11, then separately declared cooperative Dynamo8. Lease-conflict004 performed zero measurements; no failed point replay.',external_lease_conflict=p.ref(B/'external-owner-lease-conflict-001.json'),required_fresh_binding_output=str(B/'baseline-bindings-after-external-001.json'),restoration_source_manifest=p.ref(B/'baseline-after-external-source-manifest-v1.json'),cooperative_group_declaration=p.ref(B/'cooperative-dynamo8-001/declaration.json'))
d['source_files'].update({str(B/'baseline_control_after_external_v1.py'):p.sha(B/'baseline_control_after_external_v1.py'),str(Path(__file__).resolve()):p.sha(__file__)})
D=B/'baseline-reconciliation-005';p.write(D/'declaration.json',d,exclusive=True);p.need(len(q.audit(D/'declaration.json')['remaining_cells'])==10,'ten exact remaining cells required')
s=(B/'baseline_runner_reconciled_004.py').read_text().replace('baseline-reconciliation-004/declaration.json','baseline-reconciliation-005/declaration.json').replace('baseline_control_completion.py','baseline_control_after_external_v1.py');s=re.sub("RECON_SHA='[0-9a-f]+'",'RECON_SHA='+repr(p.sha(D/'declaration.json')),s);runner=B/'baseline_runner_reconciled_005.py';p.need(not runner.exists(),'new source required');runner.write_text(s);compile(s,str(runner),'exec')
paths=[runner,D/'declaration.json',B/'baseline_control_after_external_v1.py',B/'baseline_reconciliation_v3.py',B/'baseline-after-external-source-manifest-v1.json',Path(__file__).resolve()]
p.write(D/'launch-manifest.json',dict(schema='B-after-external-continuation-source-v1',created_s=time.time(),source_files={str(f):p.sha(f) for f in paths},ready_for_GPU=False,required_future_bindings=str(B/'baseline-bindings-after-external-001.json'),required_fresh_actual_qualification=True,measurement_child_unchanged=True,failure_gate_unchanged=True,cells=10,hardware_actions=False),exclusive=True)
print(json.dumps(dict(declaration=p.ref(D/'declaration.json'),launch_manifest=p.ref(D/'launch-manifest.json'),gpu_executed=False)))
