FROM pdblend-native-reference-parent-d114:2c49bd17f1be
COPY model_runner.py /usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py
COPY pdblend_diagnostics.py /usr/local/lib/python3.10/dist-packages/vllm/pdblend_diagnostics.py
COPY scheduler.py /usr/local/lib/python3.10/dist-packages/vllm/core/scheduler.py
